# Generated by Django 6.0.7 on 2026-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='code',
            field=models.CharField(default='CAT001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
