# Generated by Django 6.0.7 on 2026-08-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('projected_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sponsorship_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
